# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

stages:
  - stage: s_1
    displayName: Stage 1
    
    jobs:
      - template: dummy_template.yml
        parameters:
          p1: Apples and Oranges
      - job: my_first_job
        displayName: My First Job
        steps:
        - script: |
            echo ${{ parameters.p1 }}
          displayName: 'step_1'