# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

variables:
  - template: dummy_variables.yml

stages:
  - stage: s_1
    displayName: Stage 1
    variables: 
      - template: dummy_variables2.yml
        
    jobs:
      - template: dummy_template2.yml
        parameters:
          environment: ${{ variables.colour }}
      - template: dummy_template.yml
        parameters:
          p1: $(words)
      - job: my_first_job
        displayName: My First Job
        steps:
        - task: CmdLine@2
          displayName: 'step_1'
          inputs:
            script: 'echo $(colour) $(anima) $(words) Sky'
        - script: echo $(statement) $(words)
          displayName: 'step_2'

  - stage: s_2
    displayName: Stage 2
    variables: 
      - template: dummy_variables3.yml
    
    jobs:
      - deployment: 
        displayName: Deployment Two
        environment: ${{ variables.words }}
      - template: dummy_template.yml
        parameters:
          p1: Lychees and Raspberries are the best
      - job: my_second_job
        displayName: My Second Job
        steps:
        - script: |
            echo $(colour) $(anima) $(words) Sky
          displayName: 'step_1'
        - script: echo The environment is $(words)
          displayName: 'step_2'
        - script: echo $(song) is a hit!
          displayName: 'step_3'